// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
} from "@xata.io/client";
const DatabaseClient = buildClient();
export type DatabaseSchema = {};
const defaultOptions = {
  databaseURL:
    "https://Zohaib-Khalid-s-workspace-jheaee.eu-central-1.xata.sh/db/BitRecord",
    apiKey: process.env.XATA_API_KEY ,
    branch: "main",
};


export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options });
  }
}

let instance: XataClient | undefined = undefined;
